### ISSUE TITLE
Countup after countdown finishes

### ISSUE THREAD

**Issue by mayankjanmejay** [farhanfadila1717/slide_countdown#1]
Your plugin is awesome, I was just adding it to a 2nd app I am coding but I am a bit stuck and I could really use your help.

What I want to do is edit your plugin so it counts up after it reaches 0. Would you be able to give me any hints on how I could achieve this?

Thank you very much :)

**Comment by farhanfadila1717** [comment]
Thanks for open issues @mayankjanmejay,  onDone callback maybe help your problem, but now count up feature not available. I will add that feature soon.

**Comment by farhanfadila1717** [comment]
@mayankjanmejay this is prerelease count up feature https://pub.dev/packages/slide_countdown/versions/0.0.6-dev.1 maybe help your problem

**Comment by mayankjanmejay** [comment]
Thank you very very much :) 
I will try the OnDone callback & the new version of the plugin
