### ISSUE TITLE
about change the timer 

### ISSUE THREAD

**Issue by VimeshPolaris** [farhanfadila1717/slide_countdown#11]
This widget I added to my first screen (Home Screen) and on this screen, I called API to get the remaining time, after getting a response I add the duration into this package widget but the widget does not work properly. The widget does not accept my duration.
How can I solve it?

**Comment by farhanfadila1717** [comment]
You can try with FutureBuilder widget

**Comment by farhanfadila1717** [comment]
Fixed in [slide_countdown 0.2.4](https://pub.dev/packages/slide_countdown/versions/0.2.4)
