### ISSUE TITLE
Option to add 'countdown titles' underneath the countdown (numbers)

### ISSUE THREAD

**Issue by appcapsergen** [farhanfadila1717/slide_countdown#16]
Hello there fellow flutter'er!
I'm using your countdown timer, which works great! Though there's one thing missing for me.. being able to put the countdown titles underneath the countdown (numbers)!

A visual to represent what I'm looking for:
<img width="205" alt="image" src="https://user-images.githubusercontent.com/94898347/173408801-ebc18948-8dcf-4edf-82f9-8cbf9f4f129e.png">
_Underneath it, it simply says 'days', 'hours' and 'minutes'_

Would be super dope if this is added!

**Comment by farhanfadila1717** [comment]
Hi @appcapsergen for customization I suggest to forked this package. Because that visual change a lot of the current code base.
Feel free to modify it.
