### ISSUE TITLE
 The color value of the same color has deviation

### ISSUE THREAD

**Issue by xietian0908** [farhanfadila1717/slide_countdown#20]
<img width="288" alt="WeChat514fe871ab405fa0fe568fad1980bdb7" src="https://user-images.githubusercontent.com/64937500/182993681-ce5df236-68d7-4068-a21c-01389b7422cf.png">

Text(
                      IntlTool.tr('1:1231'),
                      style: set_font(16, color: const Color(0xff188863)),
                    ),
                    SlideCountdownSeparated(
                      separatorType: SeparatorType.symbol,
                      duration: const Duration(seconds: 10000),
                      decoration: const BoxDecoration(borderRadius: BorderRadius.all(Radius.circular(4)), color: Colors.transparent),
                      textStyle: const TextStyle(fontSize:16, color: Color(0xff188863), fontWeight: FontWeight.normal),
                      separatorStyle: const TextStyle(fontSize:16, color: Color(0xff188863)),
                      separator: ':',
                      height: 32.w,
                      width: 28.w,
                    ),

**Comment by farhanfadila1717** [comment]
Thanks @xietian0908 for created report this issue, it seems the color difference because `LinearGradient` in `Shader` widget is not correct. I has upload lastest update for fix this issue, checkout [slide_countdown: ^0.2.10](https://pub.dev/packages/slide_countdown)

**Comment by xietian0908** [comment]
@farhanfadila1717 The problem has been solved, thank you！
