### ISSUE TITLE
SlideCountdown does not work with onChanged.

### ISSUE THREAD

**Issue by melow2** [farhanfadila1717/slide_countdown#23]
SlideCountdown does not work with onChanged.
It works in SlideCountdownSeparated, but the minute is reduced not seconds.

**Comment by farhanfadila1717** [comment]
Hi @melow2 thanks for report this issue, I can reproduce this isssue, i will fix it soon in my freetime.

**Comment by farhanfadila1717** [comment]
Fixed in [slide_countdown 0.3.1](https://pub.dev/packages/slide_countdown/versions/0.3.1)
