### ISSUE TITLE
When used with onChanged, minutes rather than seconds are counted down.

### ISSUE THREAD

**Issue by melow2** [farhanfadila1717/slide_countdown#25]
When used with onChanged, minutes rather than seconds are counted down.

both SlideCountdownSeparated and SlideCountdown

**Comment by farhanfadila1717** [comment]
Hi @melow2 , i can't reproduce this bug, is looking fine in Slidecountdown v.0.3.2. can you give an code example for this bug?

this is my code sample, and it runs fine
```dart
SlideCountdown(
  duration: const Duration(seconds: 59),
  onChanged: (remainingDuration) => debugPrint(
    remainingDuration.inSeconds.toString(),
  ),
)
```

**Comment by melow2** [comment]
Hi @farhanfadila1717 
There is no bug when you enter only seconds. Please check Thank you!

**Comment by farhanfadila1717** [comment]
Still can't reproduce this bug, running fine with code example:

```dart
SlideCountdown(
  duration: const Duration(
    days: 2,
    hours: 2,
    minutes: 2,
  ),
  onChanged: (remainingDuration) => debugPrint(
    remainingDuration.inSeconds.toString(),
  ),
),
```
https://user-images.githubusercontent.com/43161050/186595991-e096633a-b006-42dd-920c-8b5dfbfec7a4.mp4

**Comment by melow2** [comment]
I think I made a mistake in my calculation. Thank you for your confirmation Be happy!

**Comment by farhanfadila1717** [comment]
@melow2 no worries. Thanks for use my package!
