### ISSUE TITLE
Feature: Add `replaceable` support.

### ISSUE THREAD

**Issue by Rosario9527** [farhanfadila1717/slide_countdown#27]
Hi There, 
[Feat]
1. Currently,  `replacement` show ONLY if `duration.inSeconds <= 0`.
could support a hook to show `replacement` earlier. something like `bool replaceable(value) { return value.inSeconds == 3600; }`.
btw, even  though `replacement` showed earlier,  keep ticker alive until `onDone`.

2. Case `separator` set to `SeparatorType.title`,  the time digits still padded as `01 hours 01 minutes`. emmm... so weird,   
 a `padDigits` option is nice, or remove pad.

[Other]
If disable `seconds` show,  `0 < duration.inSeconds < 60`,  It's show nothing.  Might keep show `0 minutes` is better,  but now it's completely OK .

thks

**Comment by farhanfadila1717** [comment]
Hi @Rosario9527,

yes i agree with you, i will add it soon.

**Comment by Rosario9527** [comment]
VTKS.
