### ISSUE TITLE
Readme Add documentation `start`, `stop`, `changeDuration`.

### ISSUE THREAD

**Issue by farhanfadila1717** [farhanfadila1717/slide_countdown#28]
Override StreamDuration example for `start`, `stop`, `changeDuration` countdown.

**Comment by farhanfadila1717** [comment]
Fixed in https://pub.dev/packages/slide_countdown/versions/0.3.4

**Comment by LidorPrototype** [comment]
I cant find a way to restart the timer, or start it only when an event happened
