### ISSUE TITLE
Bad state: Stream has already been listened to.

### ISSUE THREAD

**Issue by MaNoOoz** [farhanfadila1717/slide_countdown#29]
u need to fix this and make it brodcast stream

**Comment by farhanfadila1717** [comment]
Can you give code example?

**Comment by JgomesAT** [comment]
I need to fire again the countdown after that to achieve the done, to restart the process when the user clicks to start again, but always have this error when it tries to start again:
Bad state: Stream has already been listened to.

**Comment by farhanfadila1717** [comment]
fixed in https://pub.dev/packages/slide_countdown/versions/1.1.1
