### ISSUE TITLE
minutes display error when it is zero

### ISSUE THREAD

**Issue by zlh0223** [farhanfadila1717/slide_countdown#3]
![S11211-21222503](https://user-images.githubusercontent.com/34697394/145678221-13923cfe-64fe-4b63-82f0-0a95be8f70cd.png)

**Comment by farhanfadila1717** [comment]
Hi @zlh0223 Thanks for opening this issue, i try fix in version [v.0.0.8-dev.3](https://pub.dev/packages/slide_countdown/versions/0.0.8-dev.3)
