### ISSUE TITLE
Digits switch to the max value + 1 (60 seconds/minutes, 24 hours) before switching to the next digit (59 seconds/minutes, 23 hours)

### ISSUE THREAD

**Issue by appcapsergen** [farhanfadila1717/slide_countdown#31]
The minute and second countdown digits quickly switches from 0 to 60 before switching to 59. It should go from 0 to 59 without the switch.
I assume the same happens with hours, where it would quickly switch from 0 to 24 before switching to 23, but I haven't tested that.

This should not be possible and is just a sneaky fix that most don't see, myself included until now :P

Demonstration video:
https://user-images.githubusercontent.com/94898347/196671664-bdbdff28-f672-4cad-a81b-207f24a458a7.mov

**Comment by JgomesAT** [comment]
I have a similar problem, and furthermore the decrees is configure with the default value, but visually it seems that is decreasing 2 seconds each time

**Comment by farhanfadila1717** [comment]
fixed in https://pub.dev/packages/slide_countdown/versions/1.2.0
