### ISSUE TITLE
Feature : SeparatorType.title's Position, LTRB.

### ISSUE THREAD

**Issue by aadi-github** [farhanfadila1717/slide_countdown#33]
Hi there, Actually I am trying to show circular countdown in which I have used your Slide Coundown as the middle TimerText of Circle. The problem is SeparatorType.title shows on the right side of time only, which makes text go out of Circle if kept diameter less.

Is there any property that set SeparatorType.title position to Bottom, Up, or Left, I could not find any? As I have already used   durationTitle: DurationTitle.enShort(), but it will be nice feature if added.

**Comment by farhanfadila1717** [comment]
fixed #49
