### ISSUE TITLE
Still can't access to StreamDuration. 

### ISSUE THREAD

**Issue by Bhavukarora03** [farhanfadila1717/slide_countdown#34]
Still can't access to StreamDuration. it doesn't ignore the normal duration. Tried everything.

**Comment by spydon** [comment]
You have to add and import the StreamDuration library, from [here](https://pub.dev/packages/stream_duration/install) too.
When you have added that to your pubspec and done a `flutter pub get` you can use it like this to for example pause your timer:
```dart
     final streamDuration = StreamDuration(
      Duration(seconds: seconds),
    );
    if (!isRunning) {
      streamDuration.pause();
    }
    return SlideCountdown(
      duration: const Duration(seconds: 0),
      streamDuration: streamDuration,
    );
```
You still have to add the `duration` argument, but it is ignored (see #36).
