### ISSUE TITLE
The first second is always 00:00

### ISSUE THREAD

**Issue by RUSSCITY** [farhanfadila1717/slide_countdown#4]
When start countdown, it initialize with 00:00 value, and after first second it shows correct data. 

Please see the attached video. While initialization it has 00 sec, and then comes correctly countdown

https://user-images.githubusercontent.com/9445518/146406330-a9b97338-0346-4f8a-b707-c8aff1ff0bd6.mp4

**Comment by farhanfadila1717** [comment]
@RUSSCITY Thanks for opening issues, i'm try fix in [ver 0.0.9-dev.1](https://pub.dev/packages/slide_countdown/versions/0.0.9-dev.1), maybe it will related with this issue.

**Comment by RUSSCITY** [comment]
@farhanfadila1717 thank you!
