### ISSUE TITLE
Error in SlideCountdownSeparated 

### ISSUE THREAD

**Issue by jjvillavicencio** [farhanfadila1717/slide_countdown#43]
In my case I set a duration of 10 minutes in the `SlideCountdownSeparated` widget and the count displayed is incorrect, I changed the widget to `SlideCountdown` and the count was displayed correctly.

Plugin Versión:
slide_countdown: ^0.5.0

Code:
```
SlideCountdownSeparated(
    duration: Duration(minutes: 10),
    separatorType: SeparatorType.symbol,
    height: ctrl.responsive.hp(4),
    width: ctrl.responsive.wp(8),
    decoration: BoxDecoration(
      color: Get.theme.colorScheme.secondary,
      borderRadius: BorderRadius.circular(
        ctrl.responsive.ip(0.5),
      ),
    ),
    textStyle: TextStyle(
      color: Get.theme.colorScheme.onSecondary,
      fontSize: ctrl.responsive.ip(1.8),
      fontWeight: FontWeight.bold,
    ),
    onDone: () {
      ctrl.countDownFinish();
    },
  )
```

Error image:

![IMG_3260](https://github.com/farhanfadila1717/slide_countdown/assets/4654352/b83229e3-43f1-445c-b541-3f62c5440a26)

**Comment by farhanfadila1717** [comment]
Hi @jjvillavicencio, thanks for filling this issue, this issue fix in `0.6.0` version, check the last version of this package. https://pub.dev/packages/slide_countdown
