### ISSUE TITLE
Text for Days, hours, minutes, sec

### ISSUE THREAD

**Issue by DevMansoor** [farhanfadila1717/slide_countdown#44]
Can we add the text for days, hours, minutes, sec below the counter ?

**Comment by DevMansoor** [comment]
I have added the days like this 
` separatorType: SeparatorType.title,`
but can I add the days text below of circle?

**Comment by farhanfadila1717** [comment]
sorry for late reply, now you can customize with `RawSlideCountdown`, `RawDigitItem` in ver `0.7.0`. checkout dev version https://pub.dev/packages/slide_countdown/versions/0.7.0-dev.1
