### ISSUE TITLE
stop count down

### ISSUE THREAD

**Issue by ayechanmaung47** [farhanfadila1717/slide_countdown#5]
How to stop count down when the different duration is zero, in the SlideCountdownSeparated with zero duration the count down is moved on and goes to negative.

**Comment by farhanfadila1717** [comment]
Why you initialize with zero duration?

**Comment by ayechanmaung47** [comment]
Firstly, I got the end date from the backend, then I difference the date from the backend and current DateTime, so I get the duration, and I put the duration into the SeparatedCountdown. The duration ends onDone function is work, but when I check the countdown again the different duration has got with negative, at that time the countdown plugin still counting with negative value.

**Comment by farhanfadila1717** [comment]
instead show slidecountdown widget maybe you can handle with this 
```dart
Builder(
    builder: (context) {
       final targetDate = DateTime.now().add(Duration(hours: 2));
       final duration = targetDate.difference(targetDate);
      
      if(duration.inSeconds > 0) {
        return SlideCountdownSeparated(duration: duration);
      } else {
        return SizedBox.shrink();
      }
    }
  )

**Comment by farhanfadila1717** [comment]
Feel free to modified my package. Thanks for asking, I will close this issue.
