### ISSUE TITLE
"Bad state: Stream has already been listened to" in 1.0.2

### ISSUE THREAD

**Issue by SkyOfFeather** [farhanfadila1717/slide_countdown#51]
When I use hot reload, this error will be reported on 1.0.2. Strangely, I saw a more detailed description of 1.0.2 that fixed this error.

The following StateError was thrown building RawSlideCountdown:
Bad state: Stream has already been listened to.

**Comment by Milimeter** [comment]
Same here. Having the same error 
`═══════ Exception caught by widgets library ═══════════════════════════════════
Bad state: Stream has already been listened to.
The relevant error-causing widget was
SlideCountdownSeparated
payment_board.dart:91
════════════════════════════════════════════════════════════════════════════════`

**Comment by farhanfadila1717** [comment]
Hi thanks for filling this issue. 
Just release dev version for fix this issue checkout [slide_countdown: ^1.1.0-dev.1](https://pub.dev/packages/slide_countdown/versions/1.1.0-dev.1).

**Comment by JgomesAT** [comment]
The error is still present in 1.0.2

**Comment by farhanfadila1717** [comment]
> The error is still present in 1.0.2

Please checkout pre release version https://pub.dev/packages/slide_countdown/versions/1.1.0-dev.2

**Comment by tomquas** [comment]
i am seeing the same issue with 1.1.0.

can i be that the issue lies in package stream_duration? shouldn't the below line 

https://github.com/farhanfadila1717/stream_duration/blob/eac97d80bb7949f145733a5cdc6baddfff4a5400/lib/src/stream_duration_base.dart#L14

rather be 

```
final StreamController<Duration> _streamController =
      StreamController<Duration>().broadcast();
```

**Comment by tomquas** [comment]
the following changes to duration_stream fixes the bad state issue; however, i am still a little confused about the stream handling in general and why `SliceCountdown.didUpdateWidget` disposes streams frequently...

```
@@ -12,7 +12,7 @@ class StreamDuration {
   }

   final StreamController<Duration> _streamController =
-      StreamController<Duration>();
+      StreamController<Duration>.broadcast();

   Duration _durationLeft = Duration.zero;

@@ -52,17 +52,18 @@ class StreamDuration {
   }

   void play() {
-    _streamSubscription = Stream<Duration>.periodic(
+    _streamSubscription ??= Stream<Duration>.periodic(
       config.periodic,
       (_) {
-        if (!(_streamSubscription?.isPaused ?? true)) {
-          if (_isCountUp) {
-            return _durationLeft += config.periodic;
-          } else {
-            return _durationLeft -= config.periodic;
-          }
+        final paused = _streamSubscription?.isPaused ?? true;
+        if (paused) return _durationLeft; // was: Duration.zero; why?
+
+        if (_isCountUp) {
+          _durationLeft += config.periodic;
+        } else {
+          _durationLeft -= config.periodic;
         }
-        return Duration.zero;
+        return _durationLeft;
       },
     ).listen(
```

**Comment by tomquas** [comment]
followup: i activated `ExampleControlDuration()` in example.dart, and found the `play`, `resume` behavior to be broken.

removing `SlideCountdown#didUpdateWidget` entirely fixed this.

**Comment by farhanfadila1717** [comment]
@tomquas i have release a new version, remove didUpdateWidget from both `SlideCountdown` and `SlideCountdownSeparated`.

**Comment by tomquas** [comment]
@farhanfadila1717 thank you! may i ask: was `didUpdateWidget` an evil leftover from past, or what was the intention behind it?

**Comment by farhanfadila1717** [comment]
When I refactor `SlideCountdown` to improve performance, full customize i also upgrade `StreamDuration` package. The error seems come from `StreamDuration` reinit when `didUpdateWidget ` called.

**Comment by synstin** [comment]
@farhanfadila1717 1.2.1 After the upgrade, the error does not occur, but the textStyle property is not applied.

**Comment by farhanfadila1717** [comment]
@synstin yep the property depercated, try `style` instead

**Comment by synstin** [comment]
@farhanfadila1717 It works perfectly. Thank you.
