### ISSUE TITLE
onDone() in background state 

### ISSUE THREAD

**Issue by synstin** [farhanfadila1717/slide_countdown#52]
First of all, thank you for creating such a great package. I'm really enjoying using it.

I want to send a push message using fcm when onDone() is called in the background.

This works on Android, but on IOS, onDone() is not called when in the background.

Is there any way to have onDone() called while the app is in the background?

**Comment by farhanfadila1717** [comment]
Thank you @synstin for use my OS. It's seems dart issues, dart code can't execute/run when app is in the bg iOS. You can use other package to handle it such as https://pub.dev/packages/flutter_background_service
