### ISSUE TITLE
restart countdown

### ISSUE THREAD

**Issue by burakremzisenel** [farhanfadila1717/slide_countdown#56]
i habe trouble with restarting count down, if its done

**Comment by farhanfadila1717** [comment]
Yep its limited feature when we use Strem, i have plan to refactor `StreamDuration` with Listenable instead of Stream

**Comment by Ali-Fadaei** [comment]
any update?
or is there any workaround?!

**Comment by farhanfadila1717** [comment]
@Ali-Fadaei this issue already fixed in dev version

**Comment by Ali-Fadaei** [comment]
@farhanfadila1717. thanks for response.
I found a workaround by changing the key on Widget, until the fix come to stable version.
