### ISSUE TITLE
onDone / onChanged with RawSlideCountdown

### ISSUE THREAD

**Issue by Aging-Developer** [farhanfadila1717/slide_countdown#69]
Hi,

Firstly, just to say I really like this package, its is great.

I am struggling to see how to implement onChanged with RawSlideCountdown, all the examples are not with RawSlideCountdown, basically I just want the trigger a function when the countdown get sto zero, but onchanged doesn't seem to be supported with RawSlideCountdown, unless I am missing something obvious?

**Comment by farhanfadila1717** [comment]
hi @Aging-Developer, thanks for using my package.

When you are using `RawSlideCountdown` first you need initialize `StreamDuration`. `StreamDuration` is a stream you can use for `onChanged` method. 


```dart
late final StreamDuration streamDuration;

  @override
  void initState() {
    super.initState();
    streamDuration = StreamDuration(
      config: const StreamDurationConfig(
        countDownConfig: CountDownConfig(duration: defaultDuration),
        // similiat to `onDone`
        onDone: () => print('Countdown Finish')
      ),
    );

    // similiar to `onChanged` method
    streamDuration.durationLeft.listen(remainingDuration) {
       print('remaining duration ${remainingDuration}')
    }
  }
```
