### ISSUE TITLE
can you add localization for arabic

### ISSUE THREAD

**Issue by rulefahd** [farhanfadila1717/slide_countdown#8]
is there a way to change the locale of the numbers ?

**Comment by farhanfadila1717** [comment]
Hi @rulefahd , You can override each digit with `digitsNumber` property. it should overwrite 0-9.
try in lastest ver [slide_countdown: ^0.2.3](https://pub.dev/packages/slide_countdown)

```dart
 digitsNumber: ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'],
```


![Simulator Screen Shot - iPhone 13 - 2022-04-10 at 12 38 05](https://user-images.githubusercontent.com/43161050/162603583-f06d061b-28b6-4e72-b031-c4328abc41bf.png)

**Comment by rulefahd** [comment]
Great job , Thank you
