### ISSUE TITLE
Issue in use the DurationTitle property

### ISSUE THREAD

**Issue by VimeshPolaris** [farhanfadila1717/slide_countdown#9]
Hii their,

I'm trying to use the property of this package but it's never working.
Plz help me out with this:

 

   durationTitle: const DurationTitle(
              days: 'D',
                hours: 'H',
               minutes: 'M',
             seconds: 'S',
           ),

This text is never shown with the widget. How does it's work?
![Screenshot 2022-04-27 at 4 28 59 PM](https://user-images.githubusercontent.com/95465974/165503823-4604ad96-1e0c-4f01-b0bc-ed43a07f7957.png)

**Comment by farhanfadila1717** [comment]
have you changed the separatorType set to SeparatorType.title? @VimeshPolaris 
```dart
  separatorType: SeparatorType.title,
```
